ROOT: tox-gh-actions won't override envlist because tox is not running in GitHub Actions
py$(PYV): remove tox env folder $(@D)/.tox/py$(PYV)
py$(PYV): commands[0] $(@D)/tests> python -m pytest -v
============================= test session starts ==============================
platform sunos5 -- Python $(PYTHON_VERSION).X -- $(@D)/.tox/py$(PYV)/bin/python
cachedir: .tox/py$(PYV)/.pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('$(@D)/tests/.hypothesis/examples')
rootdir: $(@D)
configfile: tox.ini
asyncio: mode=strict
collecting ... collected 45 items

test_callback.py::test_callback_fail[s1] PASSED
test_callback.py::test_callback_fail[s2] PASSED
test_callback.py::test_callback_fail[s3] PASSED
test_callback.py::test_callback_success[s1] PASSED
test_callback.py::test_callback_success[s2] PASSED
test_callback.py::test_callback_success[s3] PASSED
test_functional_workflow.py::test_functional_work_flow PASSED
test_interruption_clean_up.py::test_interruption_cleanup PASSED
test_interruption_clean_up.py::test_interruption_does_not_cleanup PASSED
test_process_initialization.py::test_ensure_not_restart[s1] PASSED
test_process_initialization.py::test_ensure_not_restart[s2] PASSED
test_process_initialization.py::test_ensure_not_restart[s3] PASSED
test_process_initialization.py::test_popen_kwargs[s1] PASSED
test_process_initialization.py::test_popen_kwargs[s2] PASSED
test_process_initialization.py::test_popen_kwargs[s3] PASSED
test_process_initialization.py::test_runtime_error_on_start_fail[s1] PASSED
test_process_initialization.py::test_runtime_error_on_start_fail[s2] PASSED
test_process_initialization.py::test_runtime_error_on_start_fail[s3] PASSED
test_process_initialization.py::test_servers_start[s1] PASSED
test_process_initialization.py::test_servers_start[s2] PASSED
test_process_initialization.py::test_servers_start[s3] PASSED
test_process_initialization.py::test_startup_detection_max_read_lines[s1-started-21] PASSED
test_process_initialization.py::test_startup_detection_max_read_lines[s2-spam, bacon, eggs-30] PASSED
test_process_initialization.py::test_startup_detection_max_read_lines[s3-finally started-130] PASSED
test_process_termination.py::test_clean_shutdown[s1] PASSED
test_process_termination.py::test_clean_shutdown[s2] PASSED
test_process_termination.py::test_clean_shutdown[s3] PASSED
test_process_termination.py::test_return_value_on_failure[s1] PASSED
test_process_termination.py::test_return_value_on_failure[s2] PASSED
test_process_termination.py::test_return_value_on_failure[s3] PASSED
test_process_termination.py::test_sigkill_after_failed_sigterm[s1] PASSED
test_process_termination.py::test_sigkill_after_failed_sigterm[s2] PASSED
test_process_termination.py::test_sigkill_after_failed_sigterm[s3] PASSED
test_process_termination.py::test_terminate_no_pid[s1] PASSED
test_process_termination.py::test_terminate_no_pid[s2] PASSED
test_process_termination.py::test_terminate_no_pid[s3] PASSED
test_process_termination.py::test_terminate_only_parent[s1] PASSED
test_process_termination.py::test_terminate_only_parent[s2] PASSED
test_process_termination.py::test_terminate_only_parent[s3] PASSED
test_resource_cleanup.py::test_0 PASSED
test_resource_cleanup.py::test_1 PASSED
test_resource_cleanup.py::test_2 PASSED
test_startup_timeout.py::test_timeout_raise_exception[s1] PASSED
test_startup_timeout.py::test_timeout_raise_exception[s2] PASSED
test_startup_timeout.py::test_timeout_raise_exception[s3] PASSED

======== 45 passed ========
pytest-xprocess reminder::Be sure to terminate the started process by running 'pytest --xkill' if you have not explicitly done so in your fixture with 'xprocess.getinfo(<process_name>).terminate()'.
  py$(PYV): OK
  congratulations :)
