From e2c8e691218a1a6346954dc7f5b9a335967655c6 Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?Oskar=20L=C3=B6fgren?= <islander.abroad@gmail.com>
Date: Sat, 19 Dec 2020 00:04:16 +0100
Subject: [PATCH] Fix failing test in Python 2.7 (#336)

---
 test/test.py | 11 +++++++++--
 1 file changed, 9 insertions(+), 2 deletions(-)

diff --git a/test/test.py b/test/test.py
index db10272..54dd043 100755
--- a/test/test.py
+++ b/test/test.py
@@ -3,10 +3,17 @@
 
 from __future__ import absolute_import, division, print_function, unicode_literals
 
-import os, sys, shutil, argparse, subprocess, unittest, io, contextlib
+import os, sys, shutil, argparse, subprocess, unittest, contextlib
 import pexpect, pexpect.replwrap
 from tempfile import TemporaryFile, NamedTemporaryFile, mkdtemp
 
+try:
+    # Python 2
+    from cStringIO import StringIO
+except ImportError:
+    # Python 3
+    from io import StringIO
+
 TEST_DIR = os.path.abspath(os.path.dirname(__file__))  # noqa
 BASE_DIR = os.path.dirname(TEST_DIR)  # noqa
 sys.path.insert(0, BASE_DIR)  # noqa
@@ -1413,7 +1420,7 @@ def redirect_debug_stream(stream):
             finally:
                 argcomplete.debug_stream = debug_stream
 
-        test_stream = io.StringIO()
+        test_stream = StringIO()
         with redirect_debug_stream(test_stream):
             warn("My hands are tied")
 
