============================= test session starts ==============================
platform sunos5 -- Python $(PYTHON_VERSION).X -- $(PYTHON)
cachedir: .pytest_cache
rootdir: $(@D)
configfile: pyproject.toml
collecting ... collected 130 items / 1 skipped

tests/_async/test_connection.py::test_http_connection[asyncio] PASSED
tests/_async/test_connection.py::test_concurrent_requests_not_available_on_http11_connections[asyncio] PASSED
tests/_async/test_connection.py::test_write_error_with_response_sent[asyncio] PASSED
tests/_async/test_connection.py::test_write_error_without_response_sent[asyncio] PASSED
tests/_async/test_connection.py::test_http2_connection[asyncio] PASSED
tests/_async/test_connection.py::test_request_to_incorrect_origin[asyncio] PASSED
tests/_async/test_connection.py::test_connection_retries[asyncio] PASSED
tests/_async/test_connection.py::test_connection_retries_tls[asyncio] PASSED
tests/_async/test_connection.py::test_uds_connections[asyncio] PASSED
tests/_async/test_http11.py::test_http11_connection[asyncio] PASSED
tests/_async/test_http11.py::test_http11_connection_unread_response[asyncio] PASSED
tests/_async/test_http11.py::test_http11_connection_with_remote_protocol_error[asyncio] PASSED
tests/_async/test_http11.py::test_http11_connection_with_incomplete_response[asyncio] PASSED
tests/_async/test_http11.py::test_http11_connection_with_local_protocol_error[asyncio] PASSED
tests/_async/test_http11.py::test_http11_connection_handles_one_active_request[asyncio] PASSED
tests/_async/test_http11.py::test_http11_connection_attempt_close[asyncio] PASSED
tests/_async/test_http11.py::test_http11_request_to_incorrect_origin[asyncio] PASSED
tests/_async/test_http11.py::test_http11_expect_continue[asyncio] PASSED
tests/_async/test_http11.py::test_http11_upgrade_connection[asyncio] PASSED
tests/_async/test_http11.py::test_http11_upgrade_with_trailing_data[asyncio] PASSED
tests/_async/test_http11.py::test_http11_early_hints[asyncio] PASSED
tests/_async/test_http11.py::test_http11_header_sub_100kb[asyncio] PASSED
tests/_async/test_http2.py::test_http2_connection[asyncio] PASSED
tests/_async/test_http2.py::test_http2_connection_closed[asyncio] PASSED
tests/_async/test_http2.py::test_http2_connection_post_request[asyncio] PASSED
tests/_async/test_http2.py::test_http2_connection_with_remote_protocol_error[asyncio] PASSED
tests/_async/test_http2.py::test_http2_connection_with_rst_stream[asyncio] PASSED
tests/_async/test_http2.py::test_http2_connection_with_goaway[asyncio] PASSED
tests/_async/test_http2.py::test_http2_connection_with_flow_control[asyncio] PASSED
tests/_async/test_http2.py::test_http2_connection_attempt_close[asyncio] PASSED
tests/_async/test_http2.py::test_http2_request_to_incorrect_origin[asyncio] PASSED
tests/_async/test_http2.py::test_http2_remote_max_streams_update[asyncio] PASSED
tests/_async/test_http_proxy.py::test_proxy_forwarding[asyncio] PASSED
tests/_async/test_http_proxy.py::test_proxy_tunneling[asyncio] PASSED
tests/_async/test_http_proxy.py::test_proxy_tunneling_http2[asyncio] PASSED
tests/_async/test_http_proxy.py::test_proxy_tunneling_with_403[asyncio] PASSED
tests/_async/test_http_proxy.py::test_proxy_tunneling_with_auth[asyncio] PASSED
tests/_async/test_integration.py::test_request[asyncio] SKIPPED (we ...)
tests/_async/test_integration.py::test_ssl_request[asyncio] SKIPPED
tests/_async/test_integration.py::test_extra_info[asyncio] SKIPPED (...)
tests/_async/test_socks_proxy.py::test_socks5_request[asyncio] PASSED
tests/_async/test_socks_proxy.py::test_authenticated_socks5_request[asyncio] PASSED
tests/_async/test_socks_proxy.py::test_socks5_request_connect_failed[asyncio] PASSED
tests/_async/test_socks_proxy.py::test_socks5_request_failed_to_provide_auth[asyncio] PASSED
tests/_async/test_socks_proxy.py::test_socks5_request_incorrect_auth[asyncio] PASSED
tests/_sync/test_connection.py::test_http_connection PASSED
tests/_sync/test_connection.py::test_concurrent_requests_not_available_on_http11_connections PASSED
tests/_sync/test_connection.py::test_write_error_with_response_sent PASSED
tests/_sync/test_connection.py::test_write_error_without_response_sent PASSED
tests/_sync/test_connection.py::test_http2_connection PASSED
tests/_sync/test_connection.py::test_request_to_incorrect_origin PASSED
tests/_sync/test_connection.py::test_connection_retries PASSED
tests/_sync/test_connection.py::test_connection_retries_tls PASSED
tests/_sync/test_connection.py::test_uds_connections PASSED
tests/_sync/test_connection_pool.py::test_connection_pool_with_keepalive PASSED
tests/_sync/test_connection_pool.py::test_connection_pool_with_close PASSED
tests/_sync/test_connection_pool.py::test_connection_pool_with_http2 PASSED
tests/_sync/test_connection_pool.py::test_connection_pool_with_http2_goaway PASSED
tests/_sync/test_connection_pool.py::test_trace_request PASSED
tests/_sync/test_connection_pool.py::test_debug_request PASSED
tests/_sync/test_connection_pool.py::test_connection_pool_with_http_exception PASSED
tests/_sync/test_connection_pool.py::test_connection_pool_with_connect_exception PASSED
tests/_sync/test_connection_pool.py::test_connection_pool_with_immediate_expiry PASSED
tests/_sync/test_connection_pool.py::test_connection_pool_with_no_keepalive_connections_allowed PASSED
tests/_sync/test_connection_pool.py::test_connection_pool_concurrency PASSED
tests/_sync/test_connection_pool.py::test_connection_pool_concurrency_same_domain_closing PASSED
tests/_sync/test_connection_pool.py::test_connection_pool_concurrency_same_domain_keepalive PASSED
tests/_sync/test_connection_pool.py::test_unsupported_protocol PASSED
tests/_sync/test_connection_pool.py::test_connection_pool_closed_while_request_in_flight PASSED
tests/_sync/test_connection_pool.py::test_connection_pool_timeout PASSED
tests/_sync/test_connection_pool.py::test_connection_pool_timeout_zero PASSED
tests/_sync/test_connection_pool.py::test_http11_upgrade_connection PASSED
tests/_sync/test_http11.py::test_http11_connection PASSED
tests/_sync/test_http11.py::test_http11_connection_unread_response PASSED
tests/_sync/test_http11.py::test_http11_connection_with_remote_protocol_error PASSED
tests/_sync/test_http11.py::test_http11_connection_with_incomplete_response PASSED
tests/_sync/test_http11.py::test_http11_connection_with_local_protocol_error PASSED
tests/_sync/test_http11.py::test_http11_connection_handles_one_active_request PASSED
tests/_sync/test_http11.py::test_http11_connection_attempt_close PASSED
tests/_sync/test_http11.py::test_http11_request_to_incorrect_origin PASSED
tests/_sync/test_http11.py::test_http11_expect_continue PASSED
tests/_sync/test_http11.py::test_http11_upgrade_connection PASSED
tests/_sync/test_http11.py::test_http11_upgrade_with_trailing_data PASSED
tests/_sync/test_http11.py::test_http11_early_hints PASSED
tests/_sync/test_http11.py::test_http11_header_sub_100kb PASSED
tests/_sync/test_http2.py::test_http2_connection PASSED
tests/_sync/test_http2.py::test_http2_connection_closed PASSED
tests/_sync/test_http2.py::test_http2_connection_post_request PASSED
tests/_sync/test_http2.py::test_http2_connection_with_remote_protocol_error PASSED
tests/_sync/test_http2.py::test_http2_connection_with_rst_stream PASSED
tests/_sync/test_http2.py::test_http2_connection_with_goaway PASSED
tests/_sync/test_http2.py::test_http2_connection_with_flow_control PASSED
tests/_sync/test_http2.py::test_http2_connection_attempt_close PASSED
tests/_sync/test_http2.py::test_http2_request_to_incorrect_origin PASSED
tests/_sync/test_http2.py::test_http2_remote_max_streams_update PASSED
tests/_sync/test_http_proxy.py::test_proxy_forwarding PASSED
tests/_sync/test_http_proxy.py::test_proxy_tunneling PASSED
tests/_sync/test_http_proxy.py::test_proxy_tunneling_http2 PASSED
tests/_sync/test_http_proxy.py::test_proxy_tunneling_with_403 PASSED
tests/_sync/test_http_proxy.py::test_proxy_tunneling_with_auth PASSED
tests/_sync/test_integration.py::test_request SKIPPED (we have no ht...)
tests/_sync/test_integration.py::test_ssl_request SKIPPED (we have n...)
tests/_sync/test_integration.py::test_extra_info SKIPPED (we have no...)
tests/_sync/test_socks_proxy.py::test_socks5_request PASSED
tests/_sync/test_socks_proxy.py::test_authenticated_socks5_request PASSED
tests/_sync/test_socks_proxy.py::test_socks5_request_connect_failed PASSED
tests/_sync/test_socks_proxy.py::test_socks5_request_failed_to_provide_auth PASSED
tests/_sync/test_socks_proxy.py::test_socks5_request_incorrect_auth PASSED
tests/test_api.py::test_request SKIPPED (we have no httpbin)
tests/test_api.py::test_stream SKIPPED (we have no httpbin)
tests/test_api.py::test_request_with_content SKIPPED (we have no htt...)
tests/test_cancellations.py::test_connection_pool_timeout_during_request[asyncio] PASSED
tests/test_cancellations.py::test_connection_pool_timeout_during_response[asyncio] PASSED
tests/test_cancellations.py::test_h11_timeout_during_request[asyncio] PASSED
tests/test_cancellations.py::test_h11_timeout_during_response[asyncio] PASSED
tests/test_cancellations.py::test_h2_timeout_during_handshake[asyncio] XPASS
tests/test_cancellations.py::test_h2_timeout_during_request[asyncio] XPASS
tests/test_cancellations.py::test_h2_timeout_during_response[asyncio] XPASS
tests/test_models.py::test_url PASSED
tests/test_models.py::test_url_with_port PASSED
tests/test_models.py::test_url_with_invalid_argument PASSED
tests/test_models.py::test_url_cannot_include_unicode_strings PASSED
tests/test_models.py::test_request PASSED
tests/test_models.py::test_request_with_target_extension PASSED
tests/test_models.py::test_request_with_invalid_method PASSED
tests/test_models.py::test_request_with_invalid_url PASSED
tests/test_models.py::test_request_with_invalid_headers PASSED
tests/test_models.py::test_response PASSED
tests/test_models.py::test_response_sync_read PASSED
tests/test_models.py::test_response_sync_streaming PASSED

=================================== XPASSES ====================================
=========================== short test summary info ============================
======== 118 passed, 10 skipped, 3 xpassed ========
